// GENERATED by `node scripts/check_sitemap_pages.mjs --write`. check:site fails when it drifts.
// The page routes app/sitemap.ts lists. A route must not read the source tree at request time:
// see the header of scripts/check_sitemap_pages.mjs.
export const PAGE_ROUTES: readonly string[] = [
  "/",
  "/docs",
  "/learn",
  "/learn/eml",
  "/learn/eml/engineering",
  "/learn/eml/intro",
  "/learn/eml/intro/guard",
  "/learn/eml/play",
  "/superbest",
];
