#!/usr/bin/env node
// scripts/check_sitemap_pages.mjs
//
// app/sitemap.ts serves the page routes in app/sitemap-pages.ts, plus the Electronics Lab routes that
// seo.ts describes. This script derives that list from the tree and fails check:site when the
// committed file differs from what it would write.
//
// WHY THE LIST IS COMMITTED, not computed in sitemap.ts: until 2026-09-12 sitemap.ts walked app/
// with node:fs and imported next.config.mjs when the route ran. `next build` prerendered it, but
// the OpenNext Worker runs the handler on each request, and https://monogate.dev/sitemap.xml
// answered 500 (Worker version 61055eb5). Nothing a route does at request time may need the
// source tree.
//
// THE RULE. app/sitemap-pages.ts is exactly what --write would write:
//   * every app/**/page.tsx outside a dynamic ([...]) or private (_...) segment, with route
//     groups ((...)) dropped from the path;
//   * minus any route a redirect source in next.config.mjs captures (a redirect wins over a page at
//     the same path);
//   * minus NOT_LISTED, each entry with its reason. An entry that is no longer a page fails, so an
//     allowance cannot outlive its page.
//
// Usage:  node scripts/check_sitemap_pages.mjs          exit 0 current | 1 drift or self-test failure
//         node scripts/check_sitemap_pages.mjs --write  rewrite app/sitemap-pages.ts
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const APP = path.join(ROOT, "app");
const LIST = path.join(APP, "sitemap-pages.ts");

const NOT_LISTED = {
  "/archive": "a retirement notice, reached through redirects",
  "/learn/forge": "calls redirect() to /learn/eml",
};

function pagePaths(dir, route) {
  const found = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (entry.name.startsWith("[") || entry.name.startsWith("_")) continue;
      const segment = entry.name.startsWith("(") ? "" : `/${entry.name}`;
      found.push(...pagePaths(path.join(dir, entry.name), `${route}${segment}`));
    } else if (entry.name === "page.tsx") {
      found.push(route || "/");
    }
  }
  return found;
}

function captured(route, sources) {
  return sources.some((source) => {
    if (!source.endsWith("/:path*")) return route === source;
    const base = source.slice(0, -"/:path*".length);
    return route === base || route.startsWith(`${base}/`);
  });
}

function render(routes) {
  return [
    "// GENERATED by `node scripts/check_sitemap_pages.mjs --write`. check:site fails when it drifts.",
    "// The page routes app/sitemap.ts lists. A route must not read the source tree at request time:",
    "// see the header of scripts/check_sitemap_pages.mjs.",
    "export const PAGE_ROUTES: readonly string[] = [",
    ...routes.map((route) => `  ${JSON.stringify(route)},`),
    "];",
    "",
  ].join("\n");
}

function diff(want, have) {
  const w = new Set(want);
  const h = new Set(have);
  return { missing: want.filter((r) => !h.has(r)), extra: have.filter((r) => !w.has(r)) };
}

// The comparison must be able to fail: a dropped route, an added route and a changed rendering each
// have to register, and an identical list must not.
function selfTest() {
  const want = ["/", "/a", "/b"];
  const dropped = diff(want, ["/", "/a"]);
  const added = diff(want, [...want, "/c"]);
  const same = diff(want, want);
  return dropped.missing.join() === "/b" && added.extra.join() === "/c"
    && same.missing.length === 0 && same.extra.length === 0
    && render(want) !== render(["/", "/a"]);
}

const { default: nextConfig } = await import(pathToFileURL(path.join(ROOT, "next.config.mjs")).href);
const sources = (nextConfig.redirects ? await nextConfig.redirects() : []).map((r) => r.source);
const pages = pagePaths(APP, "");
const want = pages.filter((route) => !(route in NOT_LISTED) && !captured(route, sources)).sort();
const expected = render(want);

if (process.argv.includes("--write")) {
  fs.writeFileSync(LIST, expected);
  console.log(`wrote app/sitemap-pages.ts (${want.length} page routes)`);
  process.exit(0);
}

if (!selfTest()) {
  console.error("SITEMAP PAGES: SELF-TEST FAILED -- the drift comparison cannot detect a change");
  process.exit(1);
}

const problems = [];
for (const route of Object.keys(NOT_LISTED)) {
  if (!pages.includes(route)) problems.push(`NOT_LISTED names ${route}, which is no longer a page: remove the entry`);
}
const actual = fs.existsSync(LIST) ? fs.readFileSync(LIST, "utf8") : "";
if (actual !== expected) {
  const have = [...actual.matchAll(/^\s+"([^"]+)",$/gm)].map((m) => m[1]);
  const { missing, extra } = diff(want, have);
  problems.push(`app/sitemap-pages.ts is stale (missing [${missing.join(", ")}], extra [${extra.join(", ")}]). ` +
    "Run `node scripts/check_sitemap_pages.mjs --write`.");
}

if (problems.length) {
  console.error(`SITEMAP PAGES: FAIL -- ${problems.length} problem(s)`);
  for (const p of problems) console.error(`  ${p}`);
  process.exit(1);
}
console.log(`SITEMAP PAGES: CURRENT  (${want.length} page routes; ${Object.keys(NOT_LISTED).length} pages not listed, each with a reason)`);
